/*
    EASM, Eren's Educational Assembler Project
    Copyright (C) 2025 Habil Eren Türker

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef PARSER_H
#define PARSER_H

#ifdef __cplusplus
#include <string>
#include <vector>
extern "C" {
#endif

/**
 * @brief Processes a single tokenized line passed from the lexer.
 * 
 * This function takes a formatted token string (e.g., 
 * "Token: INSTR_MOV Lexeme: MOV") generated by the lexer, 
 * parses its content, and performs syntax analysis or other
 * processing depending on the token types and lexemes.
 * 
 * It is designed to be called after each line is processed by
 * the lexer and converted into a formatted string.
 * 
 * @param token_line A string containing the formatted token information 
 *                   from the lexer. Each call represents one token line.
 */
void parser_process_line(const char *token_line);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus

struct Token {
    std::string type;
    std::string lexeme;
};

void parse_token_and_lexeme(const Token& token);

#endif // __cplusplus

#endif // PARSER_H
